version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - flashcards-service-net

networks:
  flashcards-service-net: